### ISSUE TITLE
Dockerfile: zip cannot open the loaded archive

### ISSUE THREAD

**Issue by 573** [leksah/leksah#118]
In ll. 82 of Dockerfile zip the `unzip wix.zip` line throws an error:

>Step 15 : RUN mkdir ~/.wine32/drive_c/bin &&    cd ~/.wine32/drive_c/bin &&    wget --content-disposition http://wix.codeplex.com/downloads/get/1421697 &&    unzip wix.zip &&    rm wix.zip
> ---> Running in 083de9652053
>--2015-06-22 11:15:48--  http://wix.codeplex.com/downloads/get/1421697
>Resolving wix.codeplex.com (wix.codeplex.com)... 65.52.103.72
>Connecting to wix.codeplex.com (wix.codeplex.com)|65.52.103.72|:80... connected.
>
>HTTP request sent, awaiting response... 200 OK
>Length: 16320 (16K) [text/html]
>Saving to: '1421697'
>
>     0K .......... .....                                      100% 41.4K=0.4s
>
>2015-06-22 11:15:54 (41.4 KB/s) - '1421697' saved [16320/16320]
>
>unzip:  cannot find or open wix.zip, wix.zip.zip or wix.zip.ZIP.
>2015/06/22 11:15:54 The command [/bin/sh -c mkdir ~/.wine32/drive_c/bin &&    cd ~/.wine32/drive_c/bin &&    wget --content-disposition http://wix.codeplex.com/downloads/get/1421697 &&    unzip wix.zip &&    rm wix.zip] returned a non-zero code: 9

**Comment by 573** [comment]
Added https://github.com/leksah/leksah/pull/120, solves the issue.

**Comment by hamishmack** [comment]
Thanks for fixing this.  I am a little worried it might come back.  The old URL did work for a while.
