### ISSUE TITLE
Build in docker for Windows breaks

### ISSUE THREAD

**Issue by 573** [leksah/leksah#121]
... shortly before the end in the last step on MSI file assembling:

>==> default: Linking dist\build\HsColour\HsColour.exe ...
==> default: Creating package registration file:
==> default: C:\users\root\Temp\pkgConf-hscolour-11742118716.23
==> default: Installing library in C:\users\root\Application
==> default: Data\cabal\x86_64-windows-ghc-7.10.1\hscol_7cPbRrR03NzEb982Elm6on
==> default: Installing executable(s) in C:\users\root\Application Data\cabal\bi
n
==> default: Registering hscolour-1.23...
==> default: Installed hscolour-1.23
==> default: + '[wine' -eq ']'
==> default:
==> default: ./win32/makeinstaller.sh: line 3: [wine: command not found
==> default:
==> default: ++ tr -d '\r\n'
==> default:
==> default: ++ wine cmd /C echo %APPDATA%
==> default:
==> default: + WINE_APPDATA='C:\users\root\Application Data'
==> default:
==> default: + LN='ln -s'
==> default:
==> default: + LNDIR='ln -s'
==> default:
==> default: + . scripts/stage.sh
==> default:
==> default: ++ wine ghc-pkg unregister leksah
==> default:
==> default: g
==> default: h
==> default: c-
==> default: p
==> default: k
==> default: g
==> default: .
==> default: e
==> default: x
==> default: e
==> default: :
==> default:
==> default: c
==> default: a
==> default: n
==> default: n
==> default: ot
==> default:
==> default: f
==> default: i
==> default: n
==> default: d
==> default:
==> default: p
==> default: a
==> default: c
==> default: ka
==> default: ge
==> default: l
==> default: e
==> default: ks
==> default: a
==> default: h
==> default:
==> default:
==> default: ++ true
==> default:
==> default: ++ wine ghc-pkg unregister leksah-server
==> default:
==> default: g
==> default: h
==> default: c
==> default: -
==> default: p
==> default: k
==> default: g
==> default: .
==> default: e
==> default: x
==> default: e
==> default: :
==> default:
==> default: c
==> default: a
==> default: n
==> default: n
==> default: o
==> default: t
==> default:
==> default: f
==> default: i
==> default: n
==> default: d
==> default: p
==> default: a
==> default: c
==> default: ka
==> default: g
==> default: e
==> default:  l
==> default: ek
==> default: s
==> default: a
==> default: h
==> default: -
==> default: server
==> default:
==> default: ++ true
==> default:
==> default: ++ wine ghc-pkg unregister ltk
==> default:
==> default: g
==> default: h
==> default: c
==> default: -
==> default: pk
==> default: g
==> default: .
==> default: e
==> default: x
==> default: e
==> default: :
==> default:
==> default: c
==> default: a
==> default: n
==> default: n
==> default: o
==> default: t
==> default:  f
==> default: i
==> default: n
==> default: d
==> default:
==> default: p
==> default: a
==> default: ck
==> default: a
==> default: ge
==> default:
==> default: l
==> default: t
==> default: k
==> default:
==> default:
==> default: ++ true
==> default:
==> default: +++ tr -d '\r'
==> default:
==> default: +++ sed 's|version: ||'
==> default:
==> default: +++ grep '^version: ' leksah.cabal
==> default:
==> default: grep:
==> default: leksah.cabal
==> default: : No such file or directory
==> default:
==> default:
==> default: ++ export FULL_VERSION=
==> default:
==> default: ++ FULL_VERSION=
==> default:
==> default: +++ sed 's|\.[0-9]*\.[0-9]*$||'
==> default:
==> default: +++ echo
==> default:
==> default: ++ export SHORT_VERSION=
==> default:
==> default: ++ SHORT_VERSION=
==> default:
==> default: ++ export LEKSAH_X_X_X_X=leksah-
==> default:
==> default: ++ LEKSAH_X_X_X_X=leksah-
==> default:
==> default: ++ export LEKSAH_X_X=leksah-
==> default: ++ LEKSAH_X_X=leksah-
==> default:
==> default: +++ tr -d '\r'
==> default:
==> default: +++ wine ghc --numeric-version
==> default:
==> default: ++ export GHC_VER=7.10.1
==> default:
==> default: ++ GHC_VER=7.10.1
==> default:
==> default: ++ export LEKSAH_X_X_X_X_GHC_X_X_X=leksah--ghc-7.10.1
==> default:
==> default: ++ LEKSAH_X_X_X_X_GHC_X_X_X=leksah--ghc-7.10.1
==> default:
==> default: +++ sed 's|/lib *.*$||'
==> default:
==> default: +++ sed 's|^-L||'
==> default:
==> default: +++ wine pkg-config --libs-only-L gtk+-3.0
==> default:
==> default: ++ export GTK_PREFIX=Z:/usr/x86_64-w64-mingw32/sys-root/mingw
==> default:
==> default: ++ GTK_PREFIX=Z:/usr/x86_64-w64-mingw32/sys-root/mingw
==> default:
==> default: ++ echo Staging Leksah in Z:/usr/x86_64-w64-mingw32/sys-root/mingw
==> default:
==> default: Staging Leksah in Z:/usr/x86_64-w64-mingw32/sys-root/mingw
==> default: +++ uname
==> default:
==> default: ++ test Linux = Darwin
==> default:
==> default: ++ wine cabal install ./ ./vendor/ltk ./vendor/leksah-server gtk3 g
hcjs-dom jsaddle vendor/haskellVCSWrapper/vcswrapper vendor/haskellVCSGUI/vcsgui
 --with-ghc=ghc -j4 -fwebkit -f-yi -fpango -f-vty --force-reinstalls
==> default:
==> default: c
==> default: a
==> default: b
==> default: a
==> default: l
==> default: .exe: Error reading local package.
==> default: Couldn't find .cabal file in: ./
==> default:
==> default: ++ exit
==> default:
==> default: 2015/06/23 07:43:07 The command [/bin/sh -c wineserver -p1 &&    wi
ne cabal install hscolour &&    cd leksah &&    ./win32/makeinstaller.sh &&    w
ineserver -w] returned a non-zero code: 1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by hamishmack** [comment]
It looks like it can't find leksah.cabal.  That should have been copied from the host machine.  Do you have all the files from github (including the submodules), or just the Dockerfile?

**Comment by 573** [comment]
oh my... on the host ... only the Dockerfile ! Sorry for the confusion.

**Comment by 573** [comment]
Had the exact same error trying everything once again, details are: Using a docker-ready vagrant box with provisioning wherein the leksah source is cloned from github the docker image pulled and then the build is triggered.

So I don't think it's a problem of having not all files.

Vagrantfile

    # -*- mode: ruby -*-
    # vi: set ft=ruby :
    
    Vagrant.configure(2) do |config|
      config.vm.box = "ubuntu/trusty64"
      
      config.vm.provider "virtualbox" do |vb|
        vb.memory = "3068"
      end
    
      config.vm.provision "shell", :path => "build-cross-compile-image.sh"
  
      config.ssh.insert_key = false
    end

 build-cross-compile-image.sh

    #!/bin/bash
    #
    set -x
    ### Build a docker image for ubuntu i386.

    ### make sure that the required tools are installed
    apt-get install -y docker.io debootstrap dchroot

    git clone https://github.com/leksah/leksah
    cd leksah
    git submodule update --init
    wget http://dl.fedoraproject.org/pub/fedora/linux/releases/test/22_Beta/Docker/x86_64/Fedora-Docker-Base-22_Beta-20150415.x86_64.tar.xz
    docker load -i Fedora-Docker-Base-22_Beta-20150415.x86_64.tar.xz
    docker build -t leksah/build .

**Comment by 573** [comment]
Closing this as the error message seemed to result from a forgotten git submodule update, in the current version this error is not existent or reproducible.
