### ISSUE TITLE
Install leksah from sandbox into global

### ISSUE THREAD

**Issue by achirkin** [leksah/leksah#122]
I wonder what may prevent me installing leksah from sandbox?
I am using Ubuntu x64, ghc 7.10.1, leksah 0.15.0.5

I tried installing first all dependencies in a sandbox, copy all executables into global path, and then install leksah from a sandbox specifying cabal --prefix to my global path. Leksah runs nicely, but now I found a problem with hlint, which seems to have occured in past (.../.cabal-sandbox/share/x86_64-linux-ghc-7.10.1/hlint-1.9.21/HLint.hs: openFile: does not exist (No such file or directory)).

Now I wonder if this is the only bug I can encounter, and also how to solve this when building leksah?

**Comment by hamishmack** [comment]
I don't think leksah executable can be relocated without setting some environment variables.  For instance here is the code from the [osx/launcher.sh](https://github.com/leksah/leksah/blob/master/osx/launcher.sh#L50) file that does this:

    export leksah_bindir="$bundle_bin"
    export leksah_libdir="$bundle_lib/leksah/ghc"
    export leksah_datadir="$bundle_data/leksah"
    export leksah_libexecdir="$bundle_res/libexec"

    export hlint_datadir="$bundle_data/hlint"

    export vcsgui_datadir="$bundle_data/vcsgui"

Why not just add the .cabal-sandbox/bin directory to your PATH though?

**Comment by achirkin** [comment]
Thanks, yes, I see.
But at least on linux, I believe, these paths can be configured with `cabal install --prefix="..."`. I tried first just moving files from bin and share - leksah failed to run lacking some icons; then I configured with global prefix (all deps still installed locally in sandbox) - now it is running (since morning). Crashes only when I try to open hlint suggestions.
What was the problem in closed issue https://github.com/leksah/leksah/issues/36 ?

Yes, probably the best way is to use all from sandbox, but it looks to me kind of not as clean as having executable in usr/local/haskell :)

**Comment by hamishmack** [comment]
IIRC #36 was a Windows work around to get the hlint directory right without the need for a startup script (since Windows does not like them much).

Is it possible hlint was installed without setting --prefix ?

**Comment by achirkin** [comment]
I think I installed hlint globally in advance, but I am not sure anymore. 

Ok, thanks. I will try to play with reinstalling it maybe on weekend and report here.

**Comment by achirkin** [comment]
Yes, by installing all executables with `--prefix` I managed to run everything without problems
