### ISSUE TITLE
Missing source lines

### ISSUE THREAD

**Issue by varosi** [leksah/leksah#132]
Leksah 0.15.0.6 on Windows 8.1 x64

Open this Main.hs and there will be missing lines. See attached picture.
![lines](https://cloud.githubusercontent.com/assets/6051718/8635543/1022f64c-2830-11e5-9ce8-a0007633f4e3.jpg)

**Comment by varosi** [comment]
Ops, I cannot attach files here. I could send it to you by mail?

**Comment by varosi** [comment]
It has something to do with line endings may be.

**Comment by hamishmack** [comment]
Yes, please send examples by email.

**Comment by varosi** [comment]
Hello!

I have attached files that are not working on my Leksah.

Best regards,
Vassil Keremidchiev

2015-07-12 21:28 GMT+03:00 Hamish Mackenzie <notifications@github.com>:

**Comment by varosi** [comment]
This problem is fixed in 0.15.1.1.
