### ISSUE TITLE
Leksah doesn't start when ~/.bashrc uses bashisms (MacOS X)

### ISSUE THREAD

**Issue by dave4420** [leksah/leksah#138]
What happened when I tried to run Leksah from the Finder:

- no Leksah UI appeared (no window, no menu bar, no icon in the dock)
- no error message appeared
- no Leksah process appeared to be running (did not appear in Activity Monitor)

What happened when I tried to run Leksah from the command line (`/Applications/Leksah.app/Contents/MacOS/Leksah`):

- a single line error message appeared in my tty:

        /Users/dah/.bashrc: line 23: `prepend-dir': not a valid identifier

- Leksah then terminated without launching any UI etc

Relevant section of my `~/.bashrc`:

    prepend-dir() {
        local var="$1"
        local path="$2"
        if [[ -d "$path" ]] && printf ':%s:\n' "${!var}" | grep -qvF ":$path:"  ; then
            export $var="$path${!var:+:${!var}}"
        fi
    }

    prepend-dir PATH ~/.local/bin
    prepend-dir PATH ~/bin

(Line 23 is the close brace at the end of `prepend-dir`.)

Note that I use bash as my shell, and have not previously received any errors from this section of my `~/.bashrc`.

The shebang at the start of `Leksah.app/Contents/MacOS/Leksah` is

    #!/bin/sh

When I replaced it with

    #!/bin/bash

and reran Leksah, Leksah successfully started.

I have not submitted a pull request as I am unsure why the shebang is currently set to `#!/bin/sh`, and whether setting it to `#!/bin/bash` might cause problems on some systems.

(MacOS X Yosemite 10.10.4; Leksah 0.15.1.1)

**Comment by ankhers** [comment]
I'm getting something similar to this.

    $ /Applications/Leksah.app/Contents/MacOS/Leksah ; exit;
    /usr/local/etc/bash_completion.d/docker-compose: line 32: `__docker-compose_compose_file': not a valid identifier

If I uninstall fig (installed through homebrew), it appears to work properly.
