### ISSUE TITLE
Auto build is possibly broken

### ISSUE THREAD

**Issue by fehu** [leksah/leksah#143]
Leksah 0.15.1.x doesn't notice file edits.
1. create a new workspace
2. create a new package, copying "hello world" example
3. edit the Main.hs using leksah's editor

Expected: file is saved and "cabal build" is executed
Actually: nothing happens (file keeps being marked red)

(GHC 7.8.4; OpenSUSE 13.2, 3.16.7-7-desktop)

**Comment by hamishmack** [comment]
Please try 0.15.1.3 as I think this might be fixed in that version (it reverts back to the main loop used in 0.15.0.x).

**Comment by hamishmack** [comment]
Closing for now. Please let us know if this is not fixed.

**Comment by fehu** [comment]
I confirm that it works as it should in versions 0.15.1.3 and 0.15.1.4.
