### ISSUE TITLE
Memory leak of 4.7Gb+

### ISSUE THREAD

**Issue by varosi** [leksah/leksah#144]
Windows 8.1 x64
Playing with GHCi and debugging. 
Then computer with 16Gb RAM started to be unresponsive and Task manager shows that Leksah is taking 4,7Gb of RAM and counting.

**Comment by hamishmack** [comment]
Is this still happening with 0.15.1.3?

**Comment by varosi** [comment]
Currently I cannot test it, because I cannot run GHCi in some reason. And I cannot see why, because of this: https://github.com/leksah/leksah/issues/170

**Comment by varosi** [comment]
I think that this is fixed. I'm testing with 0.15.1.4 on Windows 10 x64. I'm closing it and if some other mem leak is sneaking around - I'll report it.
