### ISSUE TITLE
Latest Leksah fails to build on GHC 7.10.2 due to regex-tdfa-text

### ISSUE THREAD

**Issue by tebello-thejane** [leksah/leksah#156]
The following issue: http://hub.darcs.net/shelarcy/regex-tdfa-text/issue/1 means that Leksah cannot be built on GHC 7.10.2.

Can we remove the ``regex-tdfa-text`` dependency somehow? The issue report -- which is trivially to fix -- has been essentially ignored by the ``regex-tdfa-text`` maintainer for 2 months.

**Comment by jaccokrijnen** [comment]
regex-tdfa-text has recently been fixed :)
