### ISSUE TITLE
Cannot use GHCi debugger in Leksah 0.15.1.3 on Windows 

### ISSUE THREAD

**Issue by rickdzekman** [leksah/leksah#159]
Decided to install Leksah and give it another try today. Managed to install on GHC 7.10.2 and everything is going good so far. No apparent memory leaks, the UI has no lag, it's overall very responsive.

However, I tried to run the GHCi debugger and I got an error. Here is the complete output:

     =========================================
     Preprocessing executable 'app5' for app5-0.1.0.0...
     GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
     Ok, modules loaded: Main, API.Builder.
     <stdout>: hPutChar: invalid argument (invalid character)
     ghc.exe: warning: _tzset from msvcrt is linked instead of __imp__tzset
     ghc.exe: warning: WSACleanup from ws2_32 is linked instead of __imp_WSACleanup
     ghc.exe: warning: WSAStartup from ws2_32 is linked instead of __imp_WSAStartup
     ghc.exe: warning: WSACleanup from ws2_32 is linked instead of __imp_WSACleanup
     ghc.exe: warning: accept from ws2_32 is linked instead of __imp_accept
     ghc.exe: warning: inet_ntoa from ws2_32 is linked instead of __imp_inet_ntoa
     ghc.exe: warning: getnameinfo from ws2_32 is linked instead of __imp_getnameinfo
     ghc.exe: warning: getaddrinfo from ws2_32 is linked instead of __imp_getaddrinfo
     ghc.exe: warning: freeaddrinfo from ws2_32 is linked instead of __imp_freeaddrinfo
     =========================================

Seeing as the others are just warnings, I imagine the only error that matters is: `<stdout>: hPutChar: invalid argument (invalid character)`

**Comment by hamishmack** [comment]
Does `cabal repl` give the same error when run in the package directory?

**Comment by rickdzekman** [comment]
`cabal repl` works fine. It gives the same warnings, but doesn't give the invalid character error:

    D:\Projects\Project Haskell\app5-leksah>cabal repl
    Preprocessing executable 'app5' for app5-0.1.0.0...
    GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
    ghc.exe: warning: _tzset from msvcrt is linked instead of __imp__tzset
    ghc.exe: warning: WSACleanup from ws2_32 is linked instead of __imp_WSACleanup
    ghc.exe: warning: WSAStartup from ws2_32 is linked instead of __imp_WSAStartup
    ghc.exe: warning: WSACleanup from ws2_32 is linked instead of __imp_WSACleanup
    ghc.exe: warning: accept from ws2_32 is linked instead of __imp_accept
    ghc.exe: warning: inet_ntoa from ws2_32 is linked instead of __imp_inet_ntoa
    ghc.exe: warning: getnameinfo from ws2_32 is linked instead of __imp_getnameinfo
    ghc.exe: warning: getaddrinfo from ws2_32 is linked instead of __imp_getaddrinfo
    ghc.exe: warning: freeaddrinfo from ws2_32 is linked instead of __imp_freeaddrinfo
    Ok, modules loaded: Main.
    λ

This is an existing project, so just to make sure it wasn't my existing cabal file, I created a new project/workspace from scratch. NB. it did not include base in my `build-depends` so I had to add it manually. I removed the test suite and this is the cabal file I'm left with:

    name: test
    version: 0.0.1
    cabal-version: 1.12
    build-type: Simple
    license: AllRightsReserved
    description:
         

    executable test
        main-is: Main.hs
        build-depends:  base >=4.8 && <4.9
        default-language: Haskell2010
        hs-source-dirs: src

Standard `Main.hs`

    module Main (
        main
    ) where

    import Data.List (stripPrefix)

    -- | Simple function to create a hello message.
    -- prop> stripPrefix "Hello " (hello s) == Just s
    hello s = "Hello " ++ s

    main = do
        putStrLn (hello "World")

Same error:

    Preprocessing executable 'test' for test-0.0.1...
    GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
    Ok, modules loaded: Main.
    <stdout>: hPutChar: invalid argument (invalid character)

Meanwhile, `cabal repl`

    D:\Projects\Project Haskell\leks-test\test>cabal repl
    Preprocessing executable 'test' for test-0.0.1...
    GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
    Ok, modules loaded: Main.
    λ

**Comment by hamishmack** [comment]
Oh you changed your prompt to λ.  That will confuse Leksah.

**Comment by rickdzekman** [comment]
Ah, you're right that was the problem

**Comment by varosi** [comment]
Isn't it a way Leksah to support such cool prompt?

**Comment by hamishmack** [comment]
Quick fix is to extend [ghciParseInitialPrompt](https://github.com/leksah/leksah-server/blob/master/src/IDE/Utils/Tool.hs#L285)
