### ISSUE TITLE
Don't call register

### ISSUE THREAD

**Issue by ndmitchell** [leksah/leksah#165]
Calling `register` on a key press means that intermediate states of your library end up in the global database. That can be very damaging. If you want to do that, I suggest you automatically create sandboxes or something.

**Comment by hamishmack** [comment]
I presume you mean the "user database" (it would be even worse if we were installing stuff in the global database).

There is a "Make dependent packages" toggle button on the toolbar.  If you uncheck it Leksah does not automatically build dependent packages.  Not sure if it disables `cabal copy` and `cabal register`.  But if it does not we should change it so it does.

Indeed it would be nice to make it so the `cabal register` step would only need to be to the package database of the sandbox or stack that the package is in (so it will be less obtrusive).

Biggest sticking point with `cabal sandbox` and `stack` might be performance.  For instance if you `cabal sandbox add-source` a bunch of large packages there is no fast way to build just the packages that need to be built when a file in one of them is changed (at least not the last time I tried).

**Comment by ndmitchell** [comment]
I assume user database - but it's a user wide setting, so breaks other packages. I think by default (e.g. without any configuration changes) the IDE shouldn't do anything that harms the rest of the world.

**Comment by jaccokrijnen** [comment]
Since `new-build` this doesn't happen anymore.
