### ISSUE TITLE
Include `build-depends` field in auto-generated `.cabal` file

### ISSUE THREAD

**Issue by Gabriel439** [leksah/leksah#167]
When building a new package the `.cabal` file does not contain a `build-depends` field, so the sample module does not compile.  I would suggest adding this field with at least `base` as a dependency.

**Comment by hamishmack** [comment]
That fixes it for now, but we need to improve the package editor so it supports per component build deps (rather than just setting them all the same).

**Comment by Gabriel439** [comment]
Thank you!
