### ISSUE TITLE
Assert not interpreted

### ISSUE THREAD

**Issue by AlixBa** [leksah/leksah#169]
Hi guys,

I'm a total newbie in Haskell, just starting today and already hitting issues. I tried to use `assert` from the Control.Exception module but I don't know how to make it work. This basic snippet does not work when I try to run it inside Leksah. Is there a problem or am I missing something? Do I need to deactivate some flag or anything?

```haskell
main :: IO ()
main = assert (False) $ putStrLn "Hello"

-- prints "Hello"
-- fails on GHCi
```

Thanks.

**Comment by jaccokrijnen** [comment]
Have you imported `Control.Exception`? This works for me in leksah:

```haskell
module Main where
import Control.Exception

main = assert (False) $ putStrLn "Hello"

```

**Comment by jaccokrijnen** [comment]
Cabal (the buildtool which leksah builds on top of) seems to compile with the `-O` optimization flag (for the ghc compiler) by default. Apparently the `assert` function behaves differently when optimizations are enabled. This is what the documentation says:

>... for GHC, assertions are normally on unless optimisation is turned on with -O or the -fignore-asserts option is given ...

To fix this, go to `Package -> Edit -> Package Flags`, and add --disable-optimizations to the `configure` flags (flags are just seperated by spaces).
Then `Package -> Clean` , `Package -> Configure`, `Package -> Run`.

Good luck with your Haskell journey ;)

**Comment by AlixBa** [comment]
I saw that configuration about -O or -fignore-asserts and I was looking for a default field with one of these values. Did not think about looking for the opposite.

Anyway, it does not work `cabal: unrecognized 'configure' option `--disable-optimizations'`.
But `--disable-optimization` do :p. Thanks for that.

But since cabal compiles with -O by default, is there any downside of countering it? :o

**Comment by jaccokrijnen** [comment]
Ah thanks, I edited the previous post. 
Well, the downside is that the produced binary might be a bit slower than the optimized version. Personally, I would just avoid `assert` (I don't like program behaviour being changed by optimizations)

**Comment by AlixBa** [comment]
So, just to conclude before closing, you would use the error function in this case? https://wiki.haskell.org/Smart_constructors

**Comment by jaccokrijnen** [comment]
Using `error` would be better yes. But in general I try to avoid using `error`, there are better ways to work with errors. For instance by using the `Maybe` type:

```
metalResistor :: Bands -> Maybe Resistor
metalResistor n | n < 4 || n > 8 = error "Invalid number of resistor bands" 
                | otherwise      = Metal n
```

**Comment by jaccokrijnen** [comment]
There is an article about this: https://www.fpcomplete.com/user/commercial/content/exceptions-best-practices but it requires some advanced haskell knowledge.
If you're just starting out and learning haskell, stick with `error` for now.

**Comment by AlixBa** [comment]
Thanks a lot for everything :)
