### ISSUE TITLE
Panes | Log doesn't show log window on Windows 10

### ISSUE THREAD

**Issue by varosi** [leksah/leksah#170]
Windows 10 Home x64, Leksah 0.15.1.3 x64

This menu item doesn't do anything. And I have no way to see Log window. The same is for Output and Errors, too.

I have this output in leksah server:
Using default Yi configuration
Linked with -threaded
Reading keymap from C:\Program Files\Leksah\leksah\data\keymap.lkshk

(leksah.exe:5284): GLib-GObject-WARNING **: The property GtkSettings:gtk-menu-images is deprecated and shouldn't be used anymore. It will be removed in a future version.

(leksah.exe:5284): GLib-GObject-WARNING **: The property GtkToolButton:stock-id is deprecated and shouldn't be used anymore. It will be removed in a future version.
update workspace info called

** (leksah.exe:5284): WARNING **: Error loading plugin: 'C:\Program Files\Leksah\lib\enchant\libenchant_myspell.dll': The specified module could not be found.

Now updating system metadata ...
callCollector
***server start

**Comment by hamishmack** [comment]
Most likely it has become too small to see.  Please try [0.15.1.4](https://github.com/leksah/leksah/wiki/Leksah-0.15.1.4) as it enforces a minimum size on Panes.

**Comment by varosi** [comment]
Yes, in 0.15.1.4 it is visible, so that is fixed there. 

Now it is usable again! Thanks a lot!
