### ISSUE TITLE
"To Candy" is not working before closing source file at least once

### ISSUE THREAD

**Issue by varosi** [leksah/leksah#176]
Windows 10 Home x64, Leksah 0.15.1.4, GHC 7.10.2

1. Run Leksah
2. It automatically loads my workspace and show some opened source files
3. Press "To Candy"
4. Nothing is happen

I have to close and reopen the source file to have effect. After that it starts to work without closing anything.

**Comment by jaccokrijnen** [comment]
Hm interesting.. I can't reproduce this on Ubuntu 14.04 and Windows 7

**Comment by jaccokrijnen** [comment]
I think I reproduced it: can you try to first give focus to the text pane before pressing "To Candy" ? Does this directly apply the candy?

**Comment by varosi** [comment]
Yes, if I focus it before that - it is working.

Another thing is that "To Candy" may be it is better to be placed inside "View" menu. Every time I search it there first. I think it is more intuitive to be there.

**Comment by jaccokrijnen** [comment]
Ok thanks, I'll look into it.
I am currently reworking the menu layout, and I agree it's in the wrong place. I think that it should be in the preference window like all other preferences.
