### ISSUE TITLE
Invalid link in leksah/data/keymap.lkshk

### ISSUE THREAD

**Issue by tkemps** [leksah/leksah#185]
The link in the above file is invalid. Maybe you could reference e.g. http://www.cl.cam.ac.uk/~mgk25/ucs/keysymdef.h.

Excerpt from leksah/data/keymap.lkshk:
--The defined values for the keys can can be found at
-- http://gitweb.freedesktop.org/?p=xorg/proto/x11proto.git;a=blob_plain;f=keysymdef.h.
-- The names of the keys are the names of the macros without the prefix.

**Comment by jaccokrijnen** [comment]
Thanks!
