### ISSUE TITLE
Search (metadata) doesn't work correctly

### ISSUE THREAD

**Issue by varosi** [leksah/leksah#199]
Leksah 0.15.1.4, Windows 10 x64

1. Select a text in .hs file
2. Right click on selection
3. "Search (metadata)"
4. In Log Windows I see "Select a text first"

Which I have already done.

**Comment by jaccokrijnen** [comment]
Thanks, fixed! It was caused by the search pane taking focus before getting the selected text.

**Comment by varosi** [comment]
Thanks a lot! It's cool that this project is going forward strongly!

**Comment by jaccokrijnen** [comment]
Thank you for reporting all those issues :)
