### ISSUE TITLE
Ctrl+G instead of Ctrl+L for Go to line

### ISSUE THREAD

**Issue by varosi** [leksah/leksah#202]
This is only a proposition.
Most editors (at least under Windows) use Ctrl + G for Go to line. It will be less confusing and more standard if it could be switched to Ctrl + G.
F1 is for Help in most Windows applications, too.

**Comment by jaccokrijnen** [comment]
I agree on both. Ctrl+G is is also not yet taken for any other action.

**Comment by varosi** [comment]
Great!

**Comment by jaccokrijnen** [comment]
This has been implemented last weekend at Munihac.
