### ISSUE TITLE
leksah.lkshs, leksah.lkshw

### ISSUE THREAD

**Issue by sid-kap** [leksah/leksah#220]
After running leksah, I found files named `leksah.lkshs`, `leksah.lkshw` in my home directory. What are these files for? Is it safe to delete them? Will they be created every time I use leksah?

**Comment by JPMoresmau** [comment]
The lkshw file is the workspace definition file, holding the paths to the packages in your workspace. You shouldn't delete it, but f you do you can easily recreate a workspace and add packages to it. The lkshs is the session file, recording things like the size of panes, files opened, etc. This is created if the option to save the session is selected in the preferences. If it doesn't exist you'll just get a default layout.
