### ISSUE TITLE
Question: on (OpenSUSE Leap) Linux....  

### ISSUE THREAD

**Issue by Dutchglory** [leksah/leksah#231]
Question: on (OpenSUSE Leap) Linux.  
Can i do a system-wide installation? so all users are able to use it...  

André

**Comment by Dutchglory** [comment]
libgtksourceview-3.0-dev and libwebkitgtk-3.0-dev not available for opensuse so will not work...

**Comment by hamishmack** [comment]
I think on OpenSUSE the packages you need might be called `gtksourceview-devel` and `webkitgtk-devel`.

**Comment by Dutchglory** [comment]
there is gtksourceview-devel 2.0  and webkitgtk-devel 2.0  but not sure if this works with this code....

André

**Comment by hamishmack** [comment]
When I go [here](https://software.opensuse.org/package/gtksourceview-devel) it shows gtksourceview-devel is at 3.16.1.  Not sure what the answer for webkitgtk is.  The headers and stuff might be included in the [webkit2gtk3](https://software.opensuse.org/package/webkit2gtk3) package.

**Comment by Dutchglory** [comment]
it works :)   thank you...
