### ISSUE TITLE
New Leksah distribution

### ISSUE THREAD

**Issue by varosi** [leksah/leksah#232]
Hello!

We're impatient to get new distribution with latest fixes.
When you plan to build new ones?

**Comment by hamishmack** [comment]
I'll try to sort something out next weekend.

**Comment by varosi** [comment]
Cool!

**Comment by varosi** [comment]
We're still impatient for a new version! :-x

**Comment by varosi** [comment]
A lot of time passed after last release of Leksah. Do you plan to have new version soon? I know it's a open source project and depend on people's free time. I'm just asking purely informative and with a hope of course.

**Comment by varosi** [comment]
Cool! Thanks a lot!
