### ISSUE TITLE
HLint suggestions

### ISSUE THREAD

**Issue by flip111** [leksah/leksah#235]
Can Leksah apply HLint suggestions as described [here](http://mpickering.github.io/posts/2015-11-22-hlint-refactor.html)?

**Comment by hamishmack** [comment]
As long as there are no errors to resolve, just select the text with the green background (indicating an HLint suggestion) and press Ctrl+R.  You can select a block to fix multiple suggestions.

**Comment by flip111** [comment]
Oh that's nice, thank you
