### ISSUE TITLE
Why are there dependencies like that?

### ISSUE THREAD

**Issue by ChristopherKing42** [leksah/leksah#250]
At https://github.com/leksah/leksah/blob/6b60616e88398330b55d8e902fb42865f1ef8990/Readme.md#building-on-linux it says to

```
cabal update
cabal install Cabal cabal-install
cabal install regex-tdfa-text --ghc-options=-XFlexibleContexts
cabal install alex happy
cabal install gtk2hs-buildtools
cabal install leksah
leksah
```

couldn't this all just be dependencies?

**Comment by hamishmack** [comment]
Unfortunately no.  The packages `cabal-install`, `alex`, `happy` and `gtk2hs-buildtools` install executables used in the build process.  Cabal cannot be made to install these automatically.

The `regex-tdfa-text` needed the flag explicitly added to work around an issue it had building with ghc 7.10.  This has now been fixed so I have removed it from the instructions.
