### ISSUE TITLE
cannot determine version of ~/.bin/leksahtrue

### ISSUE THREAD

**Issue by andrewufrank** [leksah/leksah#252]
i use a simple (stdio) error report. when compile/build i get the cryptic message

cabal test '--with-ghc=leksahtrue'
Warning: cannot determine version of /home/frank/.bin/leksahtrue :
""

what does it mean and how can i get rid of? how does leksah interact with the testing approach propagated by cabal?

thank you for info/help/fix

**Comment by hamishmack** [comment]
This is part of a rather ugly hack to separate the `cabal build` and `cabal test`.  A while back `cabal test` was changed so it also ran a build first.  This meant Leksah was running `ghc ---make` twice when nothing has changed this can have a significant overhead.  Adding `'--with-ghc=leksahtrue'` is a rather hacky way to skip the `ghc --make` and preserve the old behaviour of `cabal test`.

We can probably fix this error message with a change to `leksahtrue` so that it behaves more like real `ghc` (probably needs to respond to `--version`).

**Comment by andrewufrank** [comment]
i understand the problem with building against a changing ground... why do you not ask for the leksah version? 
thank you for your time

**Comment by hamishmack** [comment]
Cabal is running `leksahtrue --version` to try to determine the version of ghc that was passed to `--with-ghc`.  It gets back nothing at all (that is what the "" is) and prints the warning.

**Comment by andrewufrank** [comment]
i see that you have a clear idea how to fix the annoyance.
thank you!

**Comment by andrewufrank** [comment]
i have now a different error message

    cabal: Cannot find the program 'ghc'. User-specified path 'leksahtrue' does
    not refer to an executable and the program is not on the system path.

**Comment by hamishmack** [comment]
That is odd.  `leksahtrue` should be installed along side `leksah` itself.  Either it is not there or (perhaps more likely) the directory containing `leksah` is not in the PATH.  Can you please check that `leksahtrue` still exists?

Perhaps we should pass the full path of leksahtrue to --with-ghc.

**Comment by andrewufrank** [comment]
there is a complication in my setup - i have copied leksah (the old version) from .cabal/bin to .bin (in order to reinstall all packages i need and which are in conflict with package versions leksah (old version) used. now i have installed the new leksah autoatically in .cabal/bin. my path is .cabal/bin and then .bin.
the error is consistent.
if you pass the path, then make it relative to the place leksah is installed (to allow moving all of leksah executables to other directories for cases where one wants/must restart with a clean ghc-pkg list (and cannot reinstall leksah for conflicts). I appreciated also that leksah does not depend on files stored in .cabal anymore; it helps.

**Comment by andrewufrank** [comment]
i moved leksah and leksahtrue to another directory (which is in the search path) but get again the message 
    ```
cabal: Cannot find the program 'ghc'. User-specified path 'leksahtrue' does
    not refer to an executable and the program is not on the system path.
```
i have reinstalled leksah, but cannot get it to work again (without moving anything). it seems that leksahtrue should only be a link to the current ghc. providing the cabal install produced leksahtrue (or another which is just a link) does not work. the complaint is that it is not found when the file is certainly available on the search $PATH. what did i wrong?

**Comment by andrewufrank** [comment]
seems to work now (jan 2018 version 16.3.1)
