### ISSUE TITLE
Could not find module ‘System.Random’

### ISSUE THREAD

**Issue by nodermann** [leksah/leksah#266]
Hi, the module is there but doesn't want to import (I checked through ghci)
https://i.imgur.com/YvA5ZEP.png

**Comment by hamishmack** [comment]
The `random` package needs to be added to your cabal file's `build-depends`.  Leksah should do this for you fi you press Ctrl+R (it parses the error message to see what package needs to be added).  Alternatively use Package -> Edit to do it manually.

**Comment by nodermann** [comment]
Thank you!, it works.
