### ISSUE TITLE
Column number in status bar is not visible.

### ISSUE THREAD

**Issue by vi-p4f** [leksah/leksah#27]
Column number in status bar is not visible because other parts are too wide. I see "..." instead of a number. I propose to move Line/Column box to the left side. This info is more useful then the current project name.
I run Leksah from FreeBsd 9 over network on Windows box.

**Comment by threestrikes** [comment]
Recommend Follow Up Tag:

This can be closed once there is a specific set of known working builds.  If FreeBsd is one of them then it stays open.
