### ISSUE TITLE
src/IDE/Utils/GUIUtils.hs:339: Not in scope: data constructor ‘PatternSynonym’

### ISSUE THREAD

**Issue by juhp** [leksah/leksah#276]
Current git master seems to fail to build for me: using Stackage Nightly at least I get

```
$ git clone git clone https://github.com/leksah/leksah.git
$ cd leksah
$ rm stack.yml
$ stack init --resolver nightly
$ stack build
:
    Preprocessing library leksah-0.15.2.0...
:
    [12 of 67] Compiling IDE.Utils.GUIUtils ( src/IDE/Utils/GUIUtils.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/IDE/Utils/GUIUtils.o )
    
src/IDE/Utils/GUIUtils.hs:339:17-30:
        Not in scope: data constructor ‘PatternSynonym’
```

leksah-0.15.2.0 builds fine (after bumping the cpphs bound).

**Comment by hamishmack** [comment]
Check that your leksah leksah-server submodule is pointing at the correct commit (should be https://github.com/leksah/leksah-server/commit/475fc79e304f16168d0a53221e6460318cf2f76f)

**Comment by juhp** [comment]
Hamish, above I am nuking/reseting the stack.yaml to use pure Stackage Nightly.
Stackage Nightly currently has leksah-server-0.15.2.0.

**Comment by juhp** [comment]
It might be nice to bump the version of leksah-server in git and make leksah require it then. :)
