### ISSUE TITLE
Pre-built binary instantly crashes

### ISSUE THREAD

**Issue by brennebeck** [leksah/leksah#28]
After downloading the prebuilt dmg from the releases page and running the app, I was greeted with the settings view. Immediately after that, leksah crashes and subsequent starts just crash as well.

``` sh
[12:19:59] ❯ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.6.3
```

Running OSX 10.9.5 and used the most recent version of leksah, 0.14.1

**Comment by threestrikes** [comment]
Recommend Closed:

Old post with no follow-up.
