### ISSUE TITLE
genBindings.sh runs extremly long without output

### ISSUE THREAD

**Issue by anfelor** [leksah/leksah#282]
While trying to install leksah from source on my Fedora 23 machine,
the script genBindings.sh from haskell-gi ran up to one and a half hour
without producing any output or terminating.

```
    $ cabal --version
cabal-install version 1.18.1.0
using version 1.18.1.5 of the Cabal library
```
All repos are up-to-date.

**Comment by duog** [comment]
I also run into this issue on Ubuntu 15.04

**Comment by hamishmack** [comment]
I think I saw this once, but can't remember what the fix was.  Can you please run:

```
cd haskell-gi/bindings/GLib
haskell-gi GLib
```

You should see:

```
	* Generating GI.GLib
		+ gi-glib.cabal
		+ cabal.config
		+ Setup.hs
		+ LICENSE
```

If it hangs instead, then please run:

```
cd haskell-gi/bindings/GLib
strace haskell-gi GLib
```

So we can see what it is doing.

**Comment by anfelor** [comment]
With `strace haskell-gi GLib 2> output.txt`
[output.txt](https://github.com/leksah/leksah/files/259249/output.txt) (5MB in 1.5 min)

**Comment by hamishmack** [comment]
I think this might have been fixed by https://github.com/haskell-gi/haskell-gi/commit/0b241e78beaf1c77d1f34262897d0174cf6eca93

**Comment by anfelor** [comment]
Indeed, that solved it! Thank you!
