### ISSUE TITLE
Building haskell-gi with a shared sandbox

### ISSUE THREAD

**Issue by jaccokrijnen** [leksah/leksah#285]
Following the new build instructions, I get at this point.

```
$ ./buildAll.sh 
cleaning...
Resolving dependencies...
Configuring gi-glib-0.2.46.14...
cabal: Encountered missing dependencies:
haskell-gi-base >=0.14 && <1
```

I assume it cannot find the dependency because I use a sandbox for all the Leksah related dependencies. Sharing the sasndbox in `.../haskell-gi` and `.../haskell-gi/bindings` does not help. Should I modify `buildAll.sh` in some way?

**Comment by hamishmack** [comment]
You should make sure that the cabal commands in `buildAll.sh` will use your sandbox.

I suspect you might have the old (0.13) `haskell-gi-base` though and `cabal update` might fix it.  [haskell-gi-base](https://hackage.haskell.org/package/haskell-gi-base) was updated from 0.13 to 0.14 hackage yesterday.

I just updated `jsaddle`, `jsaddle-dom`, `ghcjs-dom`, `gi-gk-hs` and `leksah` (including `ltk` and `haskellVCSGUI` submodules) to use `haskell-gi-base` 0.14 in github (so you will need to do a `git pull` on them too).
