### ISSUE TITLE
user error (forestStoreGetTree: path does not exist [])

### ISSUE THREAD

**Issue by JPMoresmau** [leksah/leksah#290]
Today the Leksah UI closes randomly after a couple of minutes editing. Yesterday, it worked fine, I haven't rebuilt it. The error I get in the console before being closed is:

leksah: user error (forestStoreGetTree: path does not exist [])

No precise step to reproduce, just one click in the UI randomly closes the UI. Very annoying. Should UI errors like this close down everything?

**Comment by hamishmack** [comment]
Sorry, I tracked this down and added a better `forestStoreGetForest` to `gi-gtk-hs`.  I forgot to commit and upload the change to Leksah to make it use it.
