### ISSUE TITLE
Excessive build times

### ISSUE THREAD

**Issue by jaccokrijnen** [leksah/leksah#303]
It seems like the 0.16.0.0 version of leksah builds much slower than previous versions. I did some simple timings:
## cabal build
```
# leksah 0.15.2.0
$ cabal clean && cabal install --only-dependencies && time cabal build lib:leksah
...

real	2m39.012s
user	3m15.416s
sys	0m21.696s
```
[(log)](https://gist.github.com/jaccokrijnen/8a9b7c11a225ac21648820c8523b9f1b)

```
# leksah 0.16.0.0
$ cabal clean && cabal install --only-dependencies && time cabal build lib:leksah
...

real    8m8.951s
user    10m11.436s
sys 1m3.372s
```
[(log)](https://gist.github.com/jaccokrijnen/44fdcc8cd68fefa62373ca56d4de4f0f)

## cabal repl

```
# leksah 0.15.2.0
$ cabal clean && cabal install --only-dependencies && time echo :q | cabal repl lib:leksah
...

real    0m17.492s
user    0m16.252s
sys 0m0.832s
```
[(log)](https://gist.github.com/jaccokrijnen/c880c1484cb29701a3dba093c7c9a87a)
```
# leksah 0.16.0.0
$ cabal clean && cabal install --only-dependencies && time echo :q | cabal repl lib:leksah
...

real    6m23.853s
user    6m5.260s
sys 0m3.428s
```
[(log)](https://gist.github.com/jaccokrijnen/3c370fd5b803a8453c575c2510c331e6)

In all cases I built with cabal 1.24, I can try 1.22 if that would be useful. I'm on Ubuntu with Gtk 3.16.

Especially ghci is problematic. Maybe this has to do with the port to `haskell-gi`? Maybe there is something I could change in my setup that might affect this?

**Comment by jaccokrijnen** [comment]
Thanks! That looks like a big improvement already, I wonder how it'll be on my machine :)

**Comment by hamishmack** [comment]
I have pushed a fix that includes `haskell-gi` as a submodule.  I have updated the [build instructions](https://github.com/leksah/leksah#building-from-source).  Make sure all the `gi-` modules get rebuilt the first time so the new code is generated.

**Comment by hamishmack** [comment]
I have removed also disabled the overloading for Structs now too and it seems even faster now:

```
$ time echo :q | cabal new-repl lib:leksah
...

real	0m23.690s
user	0m20.918s
sys	0m1.561s
```

**Comment by jaccokrijnen** [comment]
Great! I'm also back at the old speed :)

```
...
*IDE.HLint> Leaving GHCi.

real	0m16.973s
user	0m16.124s
sys	0m0.760s
```

**Comment by hamishmack** [comment]
This crept back in.  Flags in `cabal.project` need to be on a per package level for Cabal 1.24.
