### ISSUE TITLE
Fixing travis build

### ISSUE THREAD

**Issue by jaccokrijnen** [leksah/leksah#305]
I'm trying to fix the travis build on `travis-sudo` branch (sorry for the commit on master..). I've found that we can circumvent the whitelisting of gtksourceview by enabling sudo and just `apt-get`ing the packages manually. Was there a good reason to switch to a different build infrastructure? (f603805ec9cd5ee9fd10016303cca46bf576369a)

* It fails on the gi libraries: https://travis-ci.org/leksah/leksah/jobs/135397271

```
Failed to install gi-javascriptcore-3.0.4
Build log ( /home/travis/.cabal/logs/gi-javascriptcore-3.0.4.log ):
cabal: Entering directory '/tmp/cabal-tmp-10939/gi-javascriptcore-3.0.4'
[1 of 1] Compiling Main             ( /tmp/cabal-tmp-10939/gi-javascriptcore-3.0.4/dist/setup/setup.hs, /tmp/cabal-tmp-10939/gi-javascriptcore-3.0.4/dist/setup/Main.o )
Linking /tmp/cabal-tmp-10939/gi-javascriptcore-3.0.4/dist/setup/setup ...
Did not find a GI repository for JavaScriptCore-3.0 in
["/usr/local/share/gir-1.0","/usr/share/gir-1.0"]
cabal: Leaving directory '/tmp/cabal-tmp-10939/gi-javascriptcore-3.0.4'
```
I'm not sure what's wrong, `libgirepository1.0-dev` and `haskell-gi` installed with no problems

**Comment by hamishmack** [comment]
I think it needs `libwebkitgtk-3.0-dev`.

I have been working on the travis problem from the other end.  I started with `haskell-gi` which now builds on travis.  Next I was going to do `jsaddle` and `jsaddle-dom`.

Travis has old GIR files so we might be stuck until https://github.com/haskell-gi/haskell-gi/pull/40 is released to Hackage.

**Comment by jaccokrijnen** [comment]
Couldn't we just add `haskell-gi` as another submodule, until it's released on hackage?

**Comment by hamishmack** [comment]
> Couldn't we just add haskell-gi as another submodule until it's released on hackage?

I gave this a go.  I think current Leksah travis build would now work if travis had newer versions of Gtk+ etc.  I switched it over to use `cabal new-build` and added some caching.

**Comment by hamishmack** [comment]
It's working again now.  I used Docker so it can test on the last three releases of Ubuntu and cached the `~/.cabal` and `~/.ghc` to get the build times down a bit.  Once the haskell-gi stuff is in Hackage we can get the time down even further.
