### ISSUE TITLE
Unable to install leksah on Ubuntu

### ISSUE THREAD

**Issue by ssd532** [leksah/leksah#311]
I am following https://github.com/leksah/leksah#building-on-linux. But I am not able to build it successfully. This is a fresh installation of cabala, ghc etc.

I have created a pastebin of my terminal's output. Please check it at [here] (http://pastebin.com/25WdPbz2)

**Comment by hamishmack** [comment]
I see you are using GHC 7.6 and I am not sure if that still works.  I would recommend using GHC 7.10.3 and Cabal 1.24 with Leksah from Hackage (GHC 8.0.1 is not supported yet).  You can install them on Ubuntu by following the instructions [here](https://www.haskell.org/downloads/linux) (change `cabal-install-1.22` to `cabal-install-1.24`).  You do not need to uninstall GHC 7.6, just makes sure the newer version is in your PATH.

If you need ghc 7.6.3 to work let me know and I'll see if I can reproduce the issue.

**Comment by ssd532** [comment]
It worked with Cabal 1.24 and GHC 7.10.3. Thank you. 

I think we should mention about recommended version of Cabal and GHC somewhere in the installation wiki.
