### ISSUE TITLE
leksah build fails on archlinux

### ISSUE THREAD

**Issue by LogoiLab** [leksah/leksah#314]
Exits with code 1.

Has an issue with `GHC.IOBase` and  `Control.OldException`

```
Downloading leksah-0.4.0.2...
cabal: Entering directory '/tmp/cabal-tmp-21849/leksah-0.4.0.2'
[1 of 1] Compiling Main             ( /tmp/cabal-tmp-21849/leksah-0.4.0.2/dist/setup/setup.hs, /tmp/cabal-tmp-21849/leksah-0.4.0.2/dist/setup/Main.o )
Linking /tmp/cabal-tmp-21849/leksah-0.4.0.2/dist/setup/setup ...
Warning: leksah.cabal: A package using 'cabal-version: >=1.4' must use section
syntax. See the Cabal user guide for details.
Configuring leksah-0.4.0.2...
Warning: 'ghc-options: -prof' is not necessary and will lead to problems when
used on a library. Use the configure flag --enable-library-profiling and/or
--enable-profiling.
Building leksah-0.4.0.2...
Preprocessing executable 'leksah' for leksah-0.4.0.2...
[ 1 of 41] Compiling DeepSeq          ( src/DeepSeq.hs, dist/build/leksah/leksah-tmp/DeepSeq.o )
[ 2 of 41] Compiling Default          ( src/Default.hs, dist/build/leksah/leksah-tmp/Default.o )
[ 3 of 41] Compiling MyMissing        ( src/MyMissing.hs, dist/build/leksah/leksah-tmp/MyMissing.o )

src/MyMissing.hs:34:1: warning: [-Wtabs]
    Tab character found here, and in five further locations.
    Please use spaces instead.
[ 4 of 41] Compiling IDE.Exception    ( src/IDE/Exception.hs, dist/build/leksah/leksah-tmp/IDE/Exception.o )

src/IDE/Exception.hs:29:1: error:
    Failed to load interface for ‘Control.OldException’
    Perhaps you meant Control.Exception (from base-4.9.0.0)
    Use -v to see a list of the files searched for.

src/IDE/Exception.hs:31:1: error:
    Failed to load interface for ‘GHC.IOBase’
    Perhaps you meant GHC.Base (from base-4.9.0.0)
    Use -v to see a list of the files searched for.
cabal: Leaving directory '/tmp/cabal-tmp-21849/leksah-0.4.0.2'
Failed to install leksah-0.4.0.2
cabal: Error: some packages failed to install:
leksah-0.4.0.2 failed during the building phase. The exception was:
ExitFailure 1

```

**Comment by jaccokrijnen** [comment]
That's a very old version of leksah, have you tried installing a more recent version from hackage/github? Please see https://github.com/leksah/leksah/blob/master/Readme.md

**Comment by LogoiLab** [comment]
this was an attempt to build from hackage.

**Comment by LogoiLab** [comment]
It had an issue selecting the version:
```
[mrcbax@manjaro ~]$ cabal install leksah
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: leksah-0.15.2.0 (user goal)
next goal: base (dependency of leksah-0.15.2.0)
rejecting: base-4.9.0.0/installed-4.9... (conflict: leksah => base>=4.0.0.0 &&
<4.9)
rejecting: base-4.9.0.0, base-4.8.2.0, base-4.8.1.0, base-4.8.0.0,
base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1, base-4.6.0.0,
base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0, base-4.3.1.0,
base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0, base-4.1.0.0,
base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from non-upgradeable
package requires installed instance)
Backjump limit reached (currently 2000, change with --max-backjumps or try to
run with --reorder-goals).

```

**Comment by pouya-barzegar** [comment]
I have the same issue, installing leksah through hackage on arch linux;
`
┌─[parch@perfectp] - [~] - [Tue Jul 19, 03:46]
└─[$] <> cabal install leksah
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: leksah-0.15.2.0 (user goal)
next goal: base (dependency of leksah-0.15.2.0)
rejecting: base-4.9.0.0/installed-4.9... (conflict: leksah => base>=4.0.0.0 &&
<4.9)
rejecting: base-4.9.0.0, base-4.8.2.0, base-4.8.1.0, base-4.8.0.0,
base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1, base-4.6.0.0,
base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0, base-4.3.1.0,
base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0, base-4.1.0.0,
base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from non-upgradeable
package requires installed instance)
Backjump limit reached (currently 2000, change with --max-backjumps or try to
run with --reorder-goals).
`

**Comment by shakdwipeea** [comment]
Same issue 

```sh
$ cabal install leksah
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: leksah-0.15.2.0 (user goal)
next goal: base (dependency of leksah-0.15.2.0)
rejecting: base-4.9.0.0/installed-4.9... (conflict: leksah => base>=4.0.0.0 &&
<4.9)
rejecting: base-4.9.0.0, base-4.8.2.0, base-4.8.1.0, base-4.8.0.0,
base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1, base-4.6.0.0,
base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0, base-4.3.1.0,
base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0, base-4.1.0.0,
base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from non-upgradeable
package requires installed instance)
Dependency tree exhaustively searched.
```

**Comment by blackmirroxx** [comment]
I added  --> cabal install leksah --reorder-goals
 and keep getting : 


src/MyMissing.hs:34:1: warning: [-Wtabs]
    Tab character found here, and in five further locations.
    Please use spaces instead.
[ 4 of 41] Compiling IDE.Exception    ( src/IDE/Exception.hs, dist/build/leksah/leksah-tmp/IDE/Exception.o )

src/IDE/Exception.hs:29:1: error:
    Failed to load interface for ‘Control.OldException’
    Perhaps you meant Control.Exception (from base-4.9.0.0)
    Use -v to see a list of the files searched for.

**Comment by LogoiLab** [comment]
@blackmirroxx `--reorder-goals` seems to give you really old and broken versions of packages

**Comment by jamesmstone** [comment]
same issue here :/ any luck ?

(sorry to be that "_guy_"  - the annoying guy who bumps posts)

**Comment by jaccokrijnen** [comment]
We have verified that you can also now install leksah from source on arch, please see [here](https://github.com/leksah/leksah/blob/master/Readme.md#building-from-source)
