### ISSUE TITLE
LekSah isn't built with LekSah

### ISSUE THREAD

**Issue by gdennie** [leksah/leksah#317]
I cloned and opened the project and did not find a workspace file. Is there a LekSah in LekSah movement?

**Comment by hamishmack** [comment]
A workspace is really just a list of packages (`.cabal` files).  I am not sure we should include a standard one.  For instance if you are just working on the UI of leksah then you would only need `leksah.cabal` in the workspace.  I have about 30 packages in my workspace including some for Leksah development, but also a lot of unrelated ones.

To start working on Leksah in Leksah go to Workspace -> Add Package and add the `leksah.cabal` file to your workspace.

**Comment by gdennie** [comment]
Thanks. 
It eventually occurred to me :)

**Comment by gdennie** [comment]
How can I help out more?
