### ISSUE TITLE
Fedora packages seem really old

### ISSUE THREAD

**Issue by ftomassetti** [leksah/leksah#32]
Would be possible to have newer packages for Fedora?

**Comment by threestrikes** [comment]
Recommend Closed:

This post is old and there will be packages built in the future.

**Comment by hamishmack** [comment]
I think @juhp has updated them since this issue was first raised.

**Comment by juhp** [comment]
Just for the record, alas currently leksah is no longer in Fedora due to lack of dependencies.

My current plan is to preparing tooling to make packaging in a Fedora Copr repo easy.
