### ISSUE TITLE
Cannot install on GHC 8.0 due to regex-posix dependency

### ISSUE THREAD

**Issue by DemiMarie** [leksah/leksah#327]
Trying to install leksah on a machine with GHC 8.0 fails:

    Resolving dependencies...
    cabal: Could not resolve dependencies:
    trying: leksah-0.4.4.1 (user goal)
    next goal: regex-posix (dependency of leksah-0.4.4.1)
    Dependency tree exhaustively searched.

**Comment by A-Manning** [comment]
Try and build from source or use Leksah 0.16.0

**Comment by hamishmack** [comment]
@DemiMarie instructions for building from source (that should work for GHC 8), can be found [here](https://github.com/leksah/leksah/blob/master/Readme.md#building-from-source).
