### ISSUE TITLE
Create a dockerised version of Leksah (for easy installs)

### ISSUE THREAD

**Issue by jamesmstone** [leksah/leksah#329]
I've noticed, myself included, lots of people struggle to install a working copy of Leksah (just have a look at the open issues). As such I've tried to create a Dockerised version that just works.
Below is my attempt:
https://github.com/jamesmstone/dockerfiles/tree/master/leksah
However I'm also unffortunately having an issue ( I think similar to #328 )

Any help would be greatly appreciated.
Thanks

**Comment by jamesmstone** [comment]
Note: I'm seem to get further using `--allow-newer` as in  `cabal install leksah --allow-newer`  however I don't feel that is best practice...

**Comment by jamesmstone** [comment]
or maybe issue is more similar to #314

**Comment by hamishmack** [comment]
It might be tricky to get GUI apps working in docker.  [This might be helpfull](http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/).

You might also want to try out [Xobl Leksah](https://github.com/leksah/leksah/tree/master/xobl).

**Comment by jamesmstone** [comment]
Thanks, I've now got it working ( the key was using version 7.10.3, which I got from Xobl - thanks again!)

If you want to give it a shot, you can use the following:

> # leksah
>  [![Build Status](https://travis-ci.org/jamesmstone/dockerfiles.svg?branch=master)](https://travis-ci.org/jamesmstone/dockerfiles) [![Docker Pulls](https://img.shields.io/docker/pulls/jamesmstone/leksah.svg?maxAge=2592000)](https://hub.docker.com/r/jamesmstone/leksah/)
>  
> A dockerised version of [Leksah](http://leksah.org/)
> ## Usage
> ```
> docker run -d --rm \
> 	-v /etc/localtime:/etc/localtime:ro \
> 	-v /tmp/.X11-unix:/tmp/.X11-unix \
> 	-e DISPLAY=unix$DISPLAY \
> 	-v "$(pwd)":/home/root \
> 	-e GDK_SCALE \
> 	-e GDK_DPI_SCALE \
> 	--name leksah \
> 	jamesmstone/leksah
> ```

From: the [Readme](https://github.com/jamesmstone/dockerfiles/tree/master/leksah)
