### ISSUE TITLE
Trailing whitespace: visualize, strip [feature request]

### ISSUE THREAD

**Issue by cblp** [leksah/leksah#33]
It's a common programmers editors features:
- visualize trailing whitespace
- ~~strip trailing whitespace on save~~ -- done, but
  - reflect this in editor window on explicit save
- strip trailing whitespace only on edited lines

**Comment by threestrikes** [comment]
Recommend Closed:

Solution given.

**Comment by hamishmack** [comment]
I think we have made this work about as well as we easily can with GtkSourceView
