### ISSUE TITLE
Shift+Enter for searching backwards

### ISSUE THREAD

**Issue by jaccokrijnen** [leksah/leksah#337]
In the search bar, pressing Enter finds the next result. With the up and down buttons you can also move forward backwards through the result, but we should add Shift+Enter as well, this is a common shortcut.

This is probably set [here](https://github.com/leksah/leksah/blob/master/src/IDE/Find.hs#L360), Shift+Enter probably counts as the Enter key with the shift modifier active.

**Comment by NWuensche** [comment]
I try to solve this.

**Comment by jaccokrijnen** [comment]
My machine apparantly also has other modifiers enabled when pressing Shift+Enter

    Just "Return"
    [ModifierTypeShiftMask,ModifierTypeMod2Mask,ModifierTypeModifierReserved25Mask]

Perhaps we should just check whether the shift modifier is in the list and accept that any third modifier is also allowed.
