### ISSUE TITLE
OSX keyboard becomes unresponsive after a minute

### ISSUE THREAD

**Issue by gitfoxi** [leksah/leksah#34]
Installed the OSX binary package. After startup things I'm looking through the welcome file. All is well for a minute then the keyboard becomes unresponsive. The mouse can still scroll the text and open menus but somethings are unresponsive to clicking. Then as I'm typing this bug report the keyboard and mouse start working again.

**Comment by threestrikes** [comment]
Recommend Close:

Solution given.
