### ISSUE TITLE
Dialog won't close when pressing close button or escape

### ISSUE THREAD

**Issue by NWuensche** [leksah/leksah#358]
When you open a project in Leksah but change some code from this project in another editor, a dialog will open that tells you that a file has changed. When I try to close the dialog with the close button or the escape button, it just won't close. But i think it just shouldn't load the new file when you try to close the dialog this way

**Comment by hamishmack** [comment]
We have had a problem before when multiple dialogs were shown, it might be that.  Try moving the dialog to check if there is another one exactly the same behind it.

**Comment by NWuensche** [comment]
No, there is no other dialog behind it.

**Comment by NWuensche** [comment]
Working on this
