### ISSUE TITLE
Can not start on OS X 10.10 Yosemite

### ISSUE THREAD

**Issue by BYVoid** [leksah/leksah#37]
Hi,

I can not start Leksah 0.14.1 on OS X 10.10 Yosemite. Below is the error log in system monitor:

```
2014/10/26 23:17:55.877 leksah[29131]: *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
2014/10/26 23:17:56.628 com.apple.xpc.launchd[1]: (org.leksah.89492[29131]) Service exited with abnormal code: 1
```

Anyone has idea?

**Comment by vertexcite** [comment]
Same here, also Yosemite.
This workaround seems to work to start it from the terminal: `open /Applications/Leksah.app`

When I tried `/Applications/Leksah.app/Contents/MacOS/Leksah` from the terminal, I got a log, but no GUI (waited about half a minute, then presses ^C twice).

**Comment by threestrikes** [comment]
Recommend Closed:

This is old and not enough information to follow-up.
