### ISSUE TITLE
parens in literal strings are counted for paren matching

### ISSUE THREAD

**Issue by eamsden** [leksah/leksah#40]
When the cursor is placed on a paren in the Leksah editor, Leksah highlights what should be the matching paren. However, parens inside character and string literals are counted for the purpose of paren matching in the code.
![screenshot from 2014-11-12 13 50 32](https://cloud.githubusercontent.com/assets/54573/5016271/e79cdab0-6a72-11e4-9763-0e029edd8c42.png)

**Comment by threestrikes** [comment]
Recommend Closed:

Old and not enough information to follow-up.

**Comment by hamishmack** [comment]
I think this is a GtkSourceView bug.
