### ISSUE TITLE
0.16.1.0  crash with leksah: GError 0x0000561db5d5b460

### ISSUE THREAD

**Issue by andrewufrank** [leksah/leksah#407]
i run leksah with xfce4 and ghc 8.0.1-8 
crash occured without connection to actions.

**Comment by hamishmack** [comment]
GError is most likely something in the UI.

Can you reproduce it?

Is there anything else in the output before the crash?

Was leksah doing a background build at the time?

Had the metadata loaded at startup? (I am wondering if maybe there was a problem populating the Modules pane).

**Comment by andrewufrank** [comment]
i will try to be more attentive the next time. 
i think there was a background build and also a metadata collection.
