### ISSUE TITLE
"not a valid Win32 application"

### ISSUE THREAD

**Issue by katycoop** [leksah/leksah#415]
I just tried installing leksah-0.15.2.0-ghc-7.10.3.msi as a way to give this a quick try...

Running the resulting shortcut, all I get is a dialog box saying "C:\Leksah\bin\leksah.exe is not a valid Win32 application"

GHC is installed at C:\ghc\ghc-7.10.3, and is in the path.

![clipboard](https://cloud.githubusercontent.com/assets/24999382/21757391/e89ad138-d681-11e6-968e-a73b57551464.jpg)

OS is Win XP SP2 (yes, old school...)

**Comment by hamishmack** [comment]
We stopped making 32 bit binaries some while back.  Most recent 32 bit binary is https://github.com/leksah/leksah/wiki/leksah-0.13.4.2 and I am afraid it is unlikely to work well with recent versions of GHC.

**Comment by katycoop** [comment]
Thanks for the quick response.  I didn't see anything on the download pages indicating which builds were 32 or 64 bit.  Funny the installer didn't notice it was a 32bit OS.  Anyway, 0.13.4.2 at least starts up :)    Unfortunately it is unusable because the drop down menus do not appear when the top row of buttons are clicked.  Also, I've noticed that popup menus appear on the wrong screen (I have 3)  So I've given up on Leksah, but thank you again for getting back to me so quickly.
