### ISSUE TITLE
installing from source with stack gives "multiple candidates for Cabal entry Main.hs

### ISSUE THREAD

**Issue by andrewufrank** [leksah/leksah#417]
following the instructions to install current leksah from scratch with stack i get

frank@santafe:~/Workspace8/leksah_userspace/leksah$ stack install gtk2hs-buildtools
There were multiple candidates for the Cabal entry "Main.hs" (/home/frank/Workspace8/leksah_userspace/leksah/vendor/haskellVCSGUI/vcsgui/src/Main.hs), picking /home/frank/Workspace8/leksah_userspace/leksah/vendor/haskellVCSGUI/vcsgui/src/exe/askpass/Main.hs

is this intended behavior? is the automatic choice ok? (i use debian stretch, ghc 8.0.1 and cabal 1.24.0.0; the git clone was done right before following the instructions step by step)

i think the move to use the stack method for building is a step in the right direction. thank you!

**Comment by threestrikes** [comment]
It did the same for me but it still compiled and ran fine.  If it doesn't install make sure you cloned the repository with the --recursive parameter.  I didn't and had issues.

**Comment by metaleap** [comment]
https://github.com/gtk2hs/gtk2hs/issues would be the project to report this too
