### ISSUE TITLE
Pretty print breaks syntax hightlighting

### ISSUE THREAD

**Issue by Ptolom** [leksah/leksah#42]
For example "notElem" when printed "¬Elem" is highlighted like "Elem".

**Comment by threestrikes** [comment]
Recommend Closed:

Old and not enough information to follow-up.

**Comment by hamishmack** [comment]
It would be nice to fix this, but I suspect it might be too tricky.  The GtkSourceView syntax highlighting is done independently of Leksah's candy feature (to it the code looks like it would have the same meaning as "¬ Elem").
