### ISSUE TITLE
building 16.2.2 with stack build following instructions fails on debian jessie

### ISSUE THREAD

**Issue by andrewufrank** [leksah/leksah#436]
i did an install on a debian jessie system following the instructions which work for me on debian stretch without failing. i have identified a warning and a final error: 

warning 

 /tmp/stack1373/gi-webkit2-4.0.11/GI/WebKit2/Structs/JavascriptResult.hs:52:1: error:
        Failed to load interface for ‘GI.JavaScriptCore.Structs.GlobalContext’
        There are files missing in the ‘gi-javascriptcore-4.0.11’ package,
        try running 'ghc-pkg check'.
        Use -v to see a list of the files searched for.
    
    /tmp/stack1373/gi-webkit2-4.0.11/GI/WebKit2/Structs/JavascriptResult.hs:53:1: error:
        Failed to load interface for ‘GI.JavaScriptCore.Structs.Value’
        There are files missing in the ‘gi-javascriptcore-4.0.11’ package,
        try running 'ghc-pkg check'.
        Use -v to see a list of the files searched for.

final error (failure) 
--  While building package ltk-0.16.1.0 using:
      /home/frank/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 configure --with-ghc=/home/frank/.stack/programs/x86_64-linux/ghc-8.0.2/bin/ghc --with-ghc-pkg=/home/frank/.stack/programs/x86_64-linux/ghc-8.0.2/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/home/frank/.stack/snapshots/x86_64-linux/lts-8.0/8.0.2/pkgdb --package-db=/home/frank/Workspace8/leksah/.stack-work/install/x86_64-linux/lts-8.0/8.0.2/pkgdb --libdir=/home/frank/Workspace8/leksah/.stack-work/install/x86_64-linux/lts-8.0/8.0.2/lib --bindir=/home/frank/Workspace8/leksah/.stack-work/install/x86_64-linux/lts-8.0/8.0.2/bin --datadir=/home/frank/Workspace8/leksah/.stack-work/install/x86_64-linux/lts-8.0/8.0.2/share --libexecdir=/home/frank/Workspace8/leksah/.stack-work/install/x86_64-linux/lts-8.0/8.0.2/libexec --sysconfdir=/home/frank/Workspace8/leksah/.stack-work/install/x86_64-linux/lts-8.0/8.0.2/etc --docdir=/home/frank/Workspace8/leksah/.stack-work/install/x86_64-linux/lts-8.0/8.0.2/doc/ltk-0.16.1.0 --htmldir=/home/frank/Workspace8/leksah/.stack-work/install/x86_64-linux/lts-8.0/8.0.2/doc/ltk-0.16.1.0 --haddockdir=/home/frank/Workspace8/leksah/.stack-work/install/x86_64-linux/lts-8.0/8.0.2/doc/ltk-0.16.1.0 --dependency=Cabal=Cabal-1.24.2.0 --dependency=base=base-4.9.1.0 --dependency=base-compat=base-compat-0.9.1-B9geVZFtCvE8ERS7UcvkRz --dependency=containers=containers-0.5.7.1 --dependency=filepath=filepath-1.4.1.1 --dependency=ghc=ghc-8.0.2 --dependency=gi-cairo=gi-cairo-1.0.11-G1a1KEi6292Kmr5bB7LhbK --dependency=gi-gdk=gi-gdk-3.0.11-EdYQDtNM6dKCtBBrDEj3t7 --dependency=gi-glib=gi-glib-2.0.11-BnvjPIitPPp995KTa6j4gE --dependency=gi-gobject=gi-gobject-2.0.11-7MA5sSPWAXZ8AffzVRbstP --dependency=gi-gtk=gi-gtk-3.0.11-4QmGu8kQSxK8g37D8K6k74 --dependency=gi-gtk-hs=gi-gtk-hs-0.3.4.0-EsIBrAw8eQdIAeEL6xlXBF --dependency=haskell-gi-base=haskell-gi-base-0.20-IRPYMJiFsTS7SI5jwpSZH --dependency=mtl=mtl-2.2.1-BLKBelFsPB3BoFeSWSOYj6 --dependency=parsec=parsec-3.1.11-113irVHGgd88sRnywByDNw --dependency=pretty=pretty-1.1.3.3 --dependency=text=text-1.2.2.1-Ji7hMs2U4BkBwavd4taEVR --dependency=transformers=transformers-0.5.2.0 --enable-tests --enable-benchmarks
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/frank/Workspace8/leksah/.stack-work/logs/ltk-0.16.1.0.log

    Configuring ltk-0.16.1.0...
    Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2: The pkg-config package 'gdk-3.0'
    version >=3.18 is required but the version installed on the system is version
    3.14.5

can this be fixed without much effort? - i am happy with use on debian stretch, but i want to use leksah in teaching, where some students likely use jessie.

**Comment by hamishmack** [comment]
It looks like it has Gtk 3.14 and that is probably too old to get working easily.

**Comment by andrewufrank** [comment]
i will try with a more recent version .. thank you

**Comment by andrewufrank** [comment]
it works with the current (january 2018, 16.3.1)
