### ISSUE TITLE
Haskell GUI application runs from Leksah, but crashes when .exe invoked from command line

### ISSUE THREAD

**Issue by widc** [leksah/leksah#442]
The crash is accompanied by the following message:

_Entry Point Not Found
The procedure entry point pthread_cond_timedwait_relative_np could not be located in the dynamic link library libwinpthread-1.dll._

I posted this issue with a more detailed description here: [http://stackoverflow.com/questions/43568578/haskell-gui-application-runs-from-leksah-but-crashes-when-exe-invoked-from-com](http://stackoverflow.com/questions/43568578/haskell-gui-application-runs-from-leksah-but-crashes-when-exe-invoked-from-com) , five days ago, no response yet, so I am trying to ask for help here.

**Comment by hamishmack** [comment]
Add leksah's bin directory to your `PATH` before launching the `.exe`.  Something like:

    set PATH=%PATH%;C:\Leksah\bin`

Alternatively copy the missing DLL files from the `C:\Leksah\bin` directory into the same directory as your `.exe` file.

**Comment by widc** [comment]
Great, thank you for your help.
If I would distribute the executable to somebody who doesn't have Leksah installed, I would need to ship the exe file with the required DLLs then. Sounds easy enough.

**Comment by hamishmack** [comment]
Yes.  Alternatively they could probably get them by installing MSYS2.

**Comment by widc** [comment]
Seems so.
Win7 to Win7 quite ok, Win7 to Win8 not successful - details below:

I created a partial GUI Calculator exe file on a Win7 64bit machine.
It runs on an older Win7 64bit PC, when accompanied with about 35 DLLs (20 MB) from either of both: the c:\...Leksah\bin dir, or the c:\msys64\mingw64\bin\ dir. The Leksah set of DLLs seems to be better suited than the ones from MSYS2 (there are not so many to pick from ...).

It doesn't run on a Win8 PC, neither with the DLLs from the Win7 machine, nor with the MSYS2 DLLs installed on the Win8 PC.
