### ISSUE TITLE
Can't install on ubuntu 16.04

### ISSUE THREAD

**Issue by mixailflash** [leksah/leksah#446]
run:
 ./leksah.sh 
out:
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: leksah-0.16.2.2 (user goal)
next goal: leksah-server (user goal)
rejecting: leksah-server-0.16.1.0 (conflict: leksah => leksah-server>=0.16.2.0
&& <0.17)
rejecting: leksah-server-0.15.2.0, leksah-server-0.15.0.9,
leksah-server-0.15.0.8, leksah-server-0.15.0.7, leksah-server-0.15.0.6,
leksah-server-0.15.0.5, leksah-server-0.15.0.4, leksah-server-0.15.0.3,
leksah-server-0.15.0.2, leksah-server-0.15.0.1, leksah-server-0.14.3.2,
leksah-server-0.14.3.1, leksah-server-0.14.3.0, leksah-server-0.14.0.1,
leksah-server-0.14.0.0, leksah-server-0.13.1.1, leksah-server-0.13.1.0,
leksah-server-0.12.1.2, leksah-server-0.12.1.1, leksah-server-0.12.1.0,
leksah-server-0.12.0.5, leksah-server-0.12.0.4, leksah-server-0.12.0.3,
leksah-server-0.10.0.4, leksah-server-0.10.0.3, leksah-server-0.10.0,
leksah-server-0.8.0.8, leksah-server-0.8.0.7, leksah-server-0.8.0.6,
leksah-server-0.8.0.5, leksah-server-0.8.0.4, leksah-server-0.8.0.3,
leksah-server-0.8.0.2, leksah-server-0.8.0.1, leksah-server-0.8 (constraint
from user target requires ==0.16.1.0)
Dependency tree exhaustively searched.

**Comment by mixailflash** [comment]
Could you explain what I must doing?

**Comment by hamishmack** [comment]
I think running `git submodule update` in the leksah directory should work.

**Comment by hamishmack** [comment]
I had updated the version number of `leksah-server` but forgot to update the submodule reference in the `leksah` repository.  It was still pointing at a commit with `leksah-server` 0.16.1.0.

**Comment by mixailflash** [comment]
updated all. And now 

Resolving dependencies...
cabal: internal error when reading package index: failed to parse .cabal
fileThe package index or index cache is probably corrupt. Running cabal update
might fix it.

**Comment by hamishmack** [comment]
That is odd.  You could try `rm -rf dist-newstyle` in the leksah directory?

**Comment by mixailflash** [comment]
ok, I remove that directory and then run ./lekshh.sh
I have the same error.

**Comment by hamishmack** [comment]
Does running `cabal update` help?  What does `cabal --version` return?  What does `ghc --version` return?

**Comment by mixailflash** [comment]
Downloading the latest package list from hackage.haskell.org

cabal-install version 1.24.0.2
compiled using version 1.24.2.0 of the Cabal library 

The Glorious Glasgow Haskell Compilation System, version 7.10.3

**Comment by hamishmack** [comment]
That looks ok.  After `cabal update` does `./leksah.sh` still fail?

**Comment by mixailflash** [comment]
Yes, it's still fail.

**Comment by hamishmack** [comment]
[This](https://mail.haskell.org/pipermail/haskell-cafe/2013-September/110338.html) might be worth a try.

**Comment by mixailflash** [comment]
It doesn't help too

**Comment by mixailflash** [comment]
I installed. But I used stack with this fix 

> stack install --flag leksah:gtk-318 --flag leksah:-gtk-320
and all works fine
