### ISSUE TITLE
No artifacts on AppVeyor

### ISSUE THREAD

**Issue by qrss** [leksah/leksah#454]
The builds on AppVeyor have not had any artifact downloads available for a couple of months now.

I'm guessing it might have something to do with the line
`Error uploading cache entry to the cache storage: The maximum cache size of 1,000 MB will be exceeded.`
in the log.

**Comment by Banane9** [comment]
This is still the case :/

**Comment by hamishmack** [comment]
Should be [ok now](https://ci.appveyor.com/project/hamishmack/leksah/build/artifacts).
