### ISSUE TITLE
Multiple "file has changed on disk" prompts occuring from one event, difficult to dismiss

### ISSUE THREAD

**Issue by LijeroM** [leksah/leksah#468]
I just created a new workspace and project from scratch in the same location after closing the existing workspace, but left "Main.hs" open in a tab. This scenario has also occurred in much less specific situations, like editing the file in nano while still open.

![lots of messages](https://lijero.co/scr/leksah1.png)

I tried to drag them to see how many there were, but dragging them in itself seemed to produce more. However, at first I could drag them faster than they reproduced, so I'm wondering if it might be in some sort of timed loop until I answer them. Either that or pressing alt to drag them with xmonad somehow triggers it.

Here's another one:

![fewer messages](https://lijero.co/scr/leksah0.png)

There are more behind the one in the center, which I think was the one highlighted. I think I counted 8 total. Adding to the problem is that they can only be closed in a specific order: I'm not sure which order, but clicking in the wrong order achieves nothing. Not even the xmonad window kill (M-Shift-c) dismisses them.

The second image I managed to escape with patience, but the first I couldn't even figure out how to kill, so I had to terminate it via the terminal.

Speaking of the terminal, the logs don't provide anything helpful:

![terminal screencap](https://lijero.co/scr/leksah2.png)

I think it's a timed loop because it doesn't become a problem if I answer the first one quickly enough, and I think it's only possible to answer the newest one (I think?). I'm not sure about the required order after that though, since it's hard to keep track of all the windows. I also think it might stop after one is answered, but I don't know beyond that.

Info: a stack build as described on the readme as of Dec 24th, gtk 3.20, "Linux desktop 4.13.0-1-amd64 #1 SMP Debian 4.13.13-1 (2017-11-16) x86_64 GNU/Linux", xmonad

**Comment by hamishmack** [comment]
Please let me know if that change seems to help.  I think the background build is triggering this.  It looks like it was possible for it to be triggered again while the dialog box was displayed.   By switching from `postAsyncIDE'` to `postSyncIDE` I think the thread running the background builds should wait before retrying.

**Comment by LijeroM** [comment]
I don't know if that helped. I completely rebuilt leksah, and deleted ~/.leksah-0.16/, and deleted my leksah workspace.

![my entire xmonad workspace](https://lijero.co/scr/leksah3.png)

If you don't manage to close the prompts right away (within about 1 second of saving the externally edited file), it becomes incredibly difficult to close them. I don't think I've succeeded if I didn't manage to close at least one within 5 seconds, since they replicate faster than I can access them at that point. I'm still not sure if it's linear and I'm just slow, or if it's exponential.

Relevant log: https://lijero.co/scr/leksah3.txt
