### ISSUE TITLE
Running GHCi under Ubuntu give error message

### ISSUE THREAD

**Issue by varosi** [leksah/leksah#47]
1. Right click on .hs editor window and Eval
2. It asks to run GHCi and I give Yes
3. I got that error message in console:

> GHCi, version 7.8.3: http://www.haskell.org/ghc/  :? for help
> ghc: --interactive can't be used with -prof or -unreg.
> Usage: For basic information, try the `--help' option.

Configuration:
- Ubuntu 14.04 (64bit)
- Platform Haskell 2014.02

**Comment by threestrikes** [comment]
Recommend Closed:

Old and not enough information to follow-up.
