### ISSUE TITLE
Strange symbols in console under Ubuntu

### ISSUE THREAD

**Issue by varosi** [leksah/leksah#48]
Error messages in console have incorrect encoding:
![leksahissue1](https://cloud.githubusercontent.com/assets/6051718/5605772/d4f5c61e-9417-11e4-97cb-5679421cb44f.png)

Configuration:
- Ubuntu 14.04 (64bit)
- Haskell Platform 2014.02

**Comment by varosi** [comment]
On the screenshot you could see strange error with "\n", too.

**Comment by varosi** [comment]
My LANG is "en_US.UTF-8"

**Comment by jaccokrijnen** [comment]
@varosi is this still giving you problems on ubuntu? I can't reproduce it.

**Comment by varosi** [comment]
It was with Bulgarian locale. Did you tried different than Latin?

**Comment by varosi** [comment]
@jaccokrijnen it is possible this issue to be related to #145

**Comment by threestrikes** [comment]
Recommend Closed:

Old and not enough information to follow-up.

**Comment by hamishmack** [comment]
Please let us know if you can reproduce this with the haskell-gi based version of Leksah (>=0.16)
