### ISSUE TITLE
compilation of head (6f6f99) fails missing loadNixEnv import

### ISSUE THREAD

**Issue by andrewufrank** [leksah/leksah#483]
I have a problem with compiling the current master (https://github.com/leksah/leksah/commit/6f6f99cf5810572005755fdda8742346db7e6e99)

the error is:
```
  Buildin[g library for leksah-0.17.0.0..
    [ 7 of 68] Compiling IDE.Core.Types   ( src/IDE/Core/Types.hs, .stack-work/dist/x86_64-linux-nopie/Cabal-2.0.1.1/build/IDE/Core/Types.o )
    
    /home/frank/leksah/src/IDE/Core/Types.hs:189:29-38: error:
        Module ‘IDE.Utils.FileUtils’ does not export ‘loadNixEnv’
]
```
it would be easier if there would be a stable branch (master) and a development branch - i cannot compile...It is not sufficient to export loadNixEnv in FileUtils - it does not exist there?

**Comment by hamishmack** [comment]
I think perhaps the leksah-server git submodule was not updated somehow.  The leksah commit points to this submodule commit https://github.com/leksah/leksah-server/commit/b29dfb503badaf9213485271f111539180f3813d.  That commit does have `loadNixEnv` and exports it [here](https://github.com/leksah/leksah-server/blob/b29dfb503badaf9213485271f111539180f3813d/src/IDE/Utils/FileUtils.hs#L27).

Check the `git status` and run `git submodule update` if it looks like you have an old version of leksah-server.

**Comment by andrewufrank** [comment]
i did a new clone and it compiled - thank you. 
what is the correct git command to pull all - including the submodules? is the combination of `git pull` and 'git submodule update` the best solution? 
sorry for the incorrect alert!
