### ISSUE TITLE
Cannot build - either with GHC = 8.4.1 or GHC = 8.2.2

### ISSUE THREAD

**Issue by srb623** [leksah/leksah#485]
I noted that you had made some changes to improve support for GHC 8.4.1 so I tried to build using this version and came up with the following error:

`Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: leksah-0.17.0.0 (user goal)
[__1] trying: shakespeare-2.0.15 (dependency of leksah)
[__2] trying: template-haskell-2.13.0.0/installed-2.1... (dependency of
shakespeare)
[__3] trying: lens-4.16.1 (dependency of leksah)
[__4] next goal: jsaddle (dependency of leksah)
[__4] rejecting: jsaddle-0.9.4.0 (conflict: lens==4.16.1, jsaddle =>
lens>=3.8.5 && <4.16)
[__4] rejecting: jsaddle-0.9.3.0, jsaddle-0.9.2.1, jsaddle-0.9.2.0,
jsaddle-0.9.0.0, jsaddle-0.8.3.2, jsaddle-0.8.3.1, jsaddle-0.8.3.0,
jsaddle-0.8.0.1, jsaddle-0.8.0.0, jsaddle-0.7.0.0, jsaddle-0.6.0.1,
jsaddle-0.6.0.0, jsaddle-0.5.2.0, jsaddle-0.5.1.1, jsaddle-0.5.1.0,
jsaddle-0.5.0.2, jsaddle-0.5.0.1, jsaddle-0.5.0.0, jsaddle-0.4.0.5,
jsaddle-0.4.0.4, jsaddle-0.4.0.3, jsaddle-0.4.0.2, jsaddle-0.4.0.1,
jsaddle-0.3.0.3, jsaddle-0.3.0.2, jsaddle-0.3.0.1, jsaddle-0.3.0.0,
jsaddle-0.2.1.0, jsaddle-0.2.0.6, jsaddle-0.2.0.5, jsaddle-0.2.0.4,
jsaddle-0.2.0.3, jsaddle-0.2.0.2, jsaddle-0.2.0.1, jsaddle-0.2.0.0,
jsaddle-0.1.1.7, jsaddle-0.1.1.6, jsaddle-0.1.1.5, jsaddle-0.1.1.4,
jsaddle-0.1.1.3 (conflict: leksah => jsaddle>=0.9.4.0 && <0.10)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: leksah, lens, jsaddle,
template-haskell, shakespeare, base
`

I then went back to GHC = 8.2.2 (and have had success in the past building with this) and the following error occurs:

`[44 of 68] Compiling IDE.Package      ( src/IDE/Package.hs, dist/build/IDE/Package.o )

src/IDE/Package.hs:1377:39-50: error:
    Not in scope: ‘Glob.compile’
    No module named ‘Glob’ is imported.
     |
1377 |             patterns <- liftIO $ map (Glob.compile . (</> "*.cabal")) . extractPackageList <$> T.readFile filePath
     |                                       ^^^^^^^^^^^^

src/IDE/Package.hs:1379:31-42: error:
    Not in scope: ‘Glob.globDir’
    No module named ‘Glob’ is imported.
     |
1379 |                               Glob.globDir patterns dir
     |                               ^^^^^^^^^^^^
`

I have been trying to build via the LEKSAH.SH method.  I am running Debian Linux (testing/buster) on a 64 bit machine.

**Comment by srb623** [comment]
As I had noticed a number of commits and when I looked at them and saw that some of them related to package versions, I decided to give the build another try.  So I tried GHC = 8.4.3 and this time I had a degree of success.  The resolver did not have any issues and the packages commenced building.  The problem came when attempting to build the 'git' package, which fails with the following error:

[15 of 24] Compiling Data.Git.Types   ( Data/Git/Types.hs, dist/dist-sandbox-be5355a/build/Data/Git/Types.o )

Data/Git/Types.hs:188:10: error:
    • No instance for (Semigroup (Tree hash))
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid (Tree hash)’
    |
188 | instance Monoid (Tree hash) where
    |          ^^^^^^^^^^^^^^^^^^
cabal: Leaving directory '/tmp/cabal-tmp-2544/git-0.2.1'

I realise that this is an external package, but just wanted to comment, so that others are aware that until the owner of this package makes it compatible with 8.4.3 that compiling LEKSAH against this version will not work.

**Comment by hamishmack** [comment]
I think that is https://github.com/vincenthz/hs-git/pull/9.  If use nix to install Leksah it should use the patched branch automatically.  Alternatively clone it the branch and add a reference to the directory in `cabal.project`.

**Comment by srb623** [comment]
Given the degree of success that I had with GHC = 8.4.3, I then tried an install with GHC = 8.2.2 and this time it ran to completion.  Closing this as resolved.
