### ISSUE TITLE
OS X: No retina display support in editor

### ISSUE THREAD

**Issue by orkoden** [leksah/leksah#50]
Leksah Version 0.14.4.0

On a high resolution display on OS X (Retina) only some parts of the UI are high resolution. You can easily pick those out when looking at the text rendering. The icons are also mostly in low resolution. 

Without looking into the details, it seems to me that vanilla GTK looks correct.

Click on image to view full resolution. Low resolution parts marked in red.
![leksah on retina display](https://cloud.githubusercontent.com/assets/936793/5801372/26100f52-9fe2-11e4-93bf-372a7120fdd7.png)

Preferences is also a mixed bag. Some options are low resolution, while others are high resolution.

Low Resolution: Editor, Initial Pane Positions, Metadata
High Resolution: GUI Options, Blacklist, Build, Debug, Help

**Comment by hamishmack** [comment]
The biggest problem I find is any window with scroll bars.  [Here](https://bugs.freedesktop.org/show_bug.cgi?id=69796) is the upstream issue.

For now I find that I can improve matters slightly by choosing **Display** in **System Preferences**, then selecting **Scaled** and **More Space** (or I use my Linux VM).

**Comment by hamishmack** [comment]
@orkoden please can confirm that as of [0.15.1.4](https://github.com/leksah/leksah/wiki/Leksah-0.15.1.4) just the various button images are low res?

**Comment by threestrikes** [comment]
Recommend Closed:

Old and not enough information to follow-up.
