### ISSUE TITLE
Crash on startup?

### ISSUE THREAD

**Issue by VoltzLive** [leksah/leksah#53]
Installed Leksah today, when I tried first time start up it crashed giving this error : http://i.imgur.com/xeW8vbS.png
I uninstalled and re installed it to come back to the same issue, How do I fix it?

**Comment by hamishmack** [comment]
Did you install the ghc (included with Haskell Platform) and make sure it is in your PATH.  I think this error indicates Leksah tried to run ghc and failed.

**Comment by VoltzLive** [comment]
Path var was wrong, corrected it. Works perfectly now, Thanks.

**Comment by rtpg** [comment]
is there a way to point directly to GHC without adding it to the system PATH?
