### ISSUE TITLE
leksah use (other) sandboxes?

### ISSUE THREAD

**Issue by grguthrie** [leksah/leksah#56]
I see how to have leksah build into sandboxes, but how do I share modules across sandboxes?
i.e. I installed some modules into another main sandbox (to avoid multiple cabal version conflicts), but now those are not visible from within Leksah.

**Comment by jaccokrijnen** [comment]
You can share a sandbox of another package by clicking Package -> Sandbox -> Init Shared, and selecting the sandbox folder of the other project.
