### ISSUE TITLE
Gtk3 build flag

### ISSUE THREAD

**Issue by zudov** [leksah/leksah#58]
The description for `gtk3` flag is:
```haskell
flag gtk3
    Description: Use GTK3 rather than GTK2
```

However, it seems that the leksah executable unoptionally depends on `gtk3`:
```haskell
Executable leskah
    build-depends: leksah == 0.14.4.0, base >= 4.0.0.0 && <=4.8, gtk3 -any
```

If I understand correctly, leksah doesn't support gtk2 anymore, but the flag was not removed. 
My other guess is that flag is still needed for other components that the executable (library, bewleksah) but its description wasn't updated.

I think that the flag should either be removed completely, or the description should be changed to something less confusing (current description implies that I can build leksah without gtk3).

Unfortunately I am not enough familiar with the internal structure of leksah in order to make a reasonable PR.

Thanks.

**Comment by jaccokrijnen** [comment]
This flag was removed
