### ISSUE TITLE
Unable to load a cabal file as Workspace

### ISSUE THREAD

**Issue by varosi** [leksah/leksah#61]
Windows 8.1 x64
Leksah 0.14.0.4

Workspace | Open ... | then choose attached cabal file and you'll get this message:
![leksah1](https://cloud.githubusercontent.com/assets/6051718/6501489/a7b19ed8-c321-11e4-9232-ffc0ef4dbcae.png)

**Comment by varosi** [comment]
hm, I cannot attach here. But if you're interested I could sent you the cabal file.

**Comment by jaccokrijnen** [comment]
This option was meant to open .lkshw workspace files, not .cabal files. In HEAD, we have reordered the menu structure, such that you have "Workspace -> Add Package" to add a .cabal file to the current workspace, "File -> New -> Workspace" to create a new .lkshw, and "File -> Open -> Workspace" to open an existing .lhkhw file.

I think we could improve "File -> New -> Workspace" to display a dialog for adding the first package(s) to that new workspace (which might be an existing project or a completely new cabal project).

**Comment by varosi** [comment]
Current problem is that if you open Workspace | Open... it shows you .cabal files, too. I think if Open workspace dialog cannot open .cabal files it should not list them.

**Comment by jaccokrijnen** [comment]
Yes, that's fixed as well.
