### ISSUE TITLE
"cabal" "run" "--" cabal: unrecognised command: run (try --help)

### ISSUE THREAD

**Issue by s4wny** [leksah/leksah#63]
I just downloaded the latest version of Leksah and tried to run the default program (leksah-welcome) but when I choose `Package -> Run` I just get an error message in the log tab and nothing else happens.

```"cabal" "run" "--"
cabal: unrecognised command: run (try --help)```

Any idea why?

**Comment by hamishmack** [comment]
You probably have an old version of the cabal program in your PATH.  Try updating it with

```
cabal update
cabal install cabal-install
```

**Comment by jaccokrijnen** [comment]
Added some ghc and cabal requirements to Readme.md
