### ISSUE TITLE
32bit Windows.

### ISSUE THREAD

**Issue by BethAr** [leksah/leksah#71]
Greetings,

It seems there is no installer available for 32 bit Windows anymore. I looked through the last versions and found when the change happened. It is understandable if there is no intention in supporting Win32 anymore, but the deprecation was a bit silent and took me by surprise.

This issue, therefore, refers to the documentation and lack of upfront mention that Win64 is required.

Thank you for all your work.

**Comment by threestrikes** [comment]
Recommend Closed:

Old and resolved.

**Comment by hamishmack** [comment]
32bit windows support is unlikely to happen.  Download page has been updated to say "Windows (64 bit)"
