### ISSUE TITLE
Support Homebrew on Mac OS X?

### ISSUE THREAD

**Issue by FranklinChen** [leksah/leksah#73]
The build instructions for Mac OS X involve MacPorts, but I use Homebrew. Perhaps someone can provide instructions for Homebrew also?

**Comment by hamishmack** [comment]
We can't support building Leksah with Homebrew until there is a documented way to install a recent version of WebKitGTK+ with Homebrew.  Please re-open this issue if you find instructions on how to do that.  For now Homebrew users will have to use the Leksah prebuilt binaries or install MacPorts as well.
