### ISSUE TITLE
Use $PATH from .bashrc as well

### ISSUE THREAD

**Issue by k-bx** [leksah/leksah#74]
Installed and opened Leksah with default project it provides. Doing build produces this error:

https://i.imgur.com/rylLto3.png

```
cabal build
cabal: The program 'ghc' version >=6.4 is required but it could not be found.
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
```

So, does it need some help with PATHs or something?

Thanks!

**Comment by hamishmack** [comment]
Yes add ghc to your PATH in your ~/.profile (may require you to log out and back in) or in the advance section of the "System" control panel item on Windows.  I will leave this issue open though as Leksah should have a better way of dealing with this.

**Comment by k-bx** [comment]
@hamishmack the thing is that my ghc is at `/usr/local/bin/ghc`, so it should be in PATH by default, shouldn't it?

**Comment by hamishmack** [comment]
It might depend how you leksah.  It might be that `/usr/local/bin` is added in your `.bash_profile`.  Try running `cabal build` in the package directory from a terminal window.  If that works then try running `leksah` from the same window (`/Applications/Leksah.app/Contents/MacOS/Leksah` on OS X).

**Comment by k-bx** [comment]
@hamishmack you're right, only that it's not `.bash_profile`, but rather global `/etc/profile` script which sets those paths. So, would be super-nice if Leksah could do something similar to this emacs lib https://github.com/purcell/exec-path-from-shell

**Comment by infinity0** [comment]
I don't think this is leksah's problem. `.bashrc` is bash-specific, the correct place to augment your `PATH` is `.profile`. Some desktop environments ignore this file and use `.xprofile` instead, perhaps you can try that (or `ln -sf ~/.profile ~/.xprofile`).

**Comment by jaccokrijnen** [comment]
I've added an issue for looking in .bashrc and similar shell config files (#320)
