### ISSUE TITLE
Missing modules from executable in cabal file

### ISSUE THREAD

**Issue by varosi** [leksah/leksah#88]
I have .cabal file with only Executable inside (no libraries).
main-is: Backend/Main.hs

GHCi is including all imported modules when it is ran. When I build cabal file - everything is correctly linked and imported. But in Modules Pane I see only Main module and all other modules from my executable are missing.

**Comment by hamishmack** [comment]
Please add the modules to the Executable's `other-modules:` in the .cabal file.  I believe this is a requirement for `cabal sdist` to work too.  GHC and GHCi can find them by chasing the imports, but cabal and leksah do not.

**Comment by varosi** [comment]
Okay, thank you!
