### ISSUE TITLE
Automatic reload of source files on change (after ask)

### ISSUE THREAD

**Issue by varosi** [leksah/leksah#92]
Under Windows most IDEs are doing automated update (after question dialog) of source files if someone change the file from outside editor, or from checking out different commit in GIT while Leksah is opened.

**Comment by hamishmack** [comment]
I think we have this, but perhaps only while background build is enabled.  Can you please check?

If so we just need to extend it to work when background build is disabled.

**Comment by threestrikes** [comment]
Recommend Close:

Old post with no follow up.
