### ISSUE TITLE
Mac OS X download unavailable

### ISSUE THREAD

**Issue by FranklinChen** [leksah/leksah#97]
These do not exist:

    leksah-0.15.0.2-ghc-7.10.1.dmg for use with ghc 7.10.1
    leksah-0.15.0.2-ghc-7.8.3.dmg for use with ghc 7.8.3

**Comment by hamishmack** [comment]
Oops put them in the wrong dir.  Try now.

**Comment by FranklinChen** [comment]
Thanks!
