### ISSUE TITLE
Improve feedback when module name is invalid

### ISSUE THREAD

**Issue by hamishmack** [leksah/leksah#99]
From Kiuhnm on reddit
> For instance try to create a module with the name "chapter_2". It should fail because that's not a valid name for a module. But a beginner doesn't know that. Leksah doesn't complain but the module isn't created.

A message is goes to the Log pane, but the log pane is not brought into focus.  It would be better if we could validate the module name in the Add Module dialog and display something there as well as disabling the OK button.

**Comment by jaccokrijnen** [comment]
Added in 8f5eb92
